spring:
  application:
    name: ClayERP Core
  datasource:
    url: jdbc:postgresql://localhost:5432/clayerp-dev
    username: clayerp
    password: dev-123

  jpa:
    hibernate:
      ddl-auto: none

  messages:
    basename: messages/messages
    encoding: UTF-8
    fallback-to-system-locale: false

  mvc:
    locale: pt_BR
    locale-resolver: fixed

  liquibase:
    change-log: classpath:db/changelog/master.yaml

server:
  port: 8080