spring:
  application:
    name: ClayERP Core
  datasource:
    url: jdbc:postgresql://localhost:5432/clayerp-dev
    username: clayerp
    password: dev-123

  jpa:
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:db/changelog/master.yaml

server:
  port: 8080