version: "3.9"

services:

  postgres:
    image: postgres:16
    container_name: clayerp-postgres

    environment:
      POSTGRES_DB: clayerp-dev
      POSTGRES_USER: clayerp
      POSTGRES_PASSWORD: dev-123

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: